version: "3.3"
services:

  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  slurmdbd:
    image: sinaiiidgst/slurm:latest
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
      - data_dir:/var/data
    expose:
      - "6819"
    depends_on:
      - mysql

  slurmctld:
    image: sinaiiidgst/slurm:latest
    command: ["slurm-cromwell.sh"]
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - data_dir:/var/data
      - docker:/var/run/docker.sock
    expose:
      - "6817"
      - "8000"
    depends_on:
      - "slurmdbd"

  c1:
    image: sinaiiidgst/slurm:latest
    command: ["slurmd"]
    hostname: c1
    container_name: c1
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - data_dir:/var/data
      - docker:/var/run/docker.sock
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

  c2:
    image: sinaiiidgst/slurm:latest
    command: ["slurmd"]
    hostname: c2
    container_name: c2
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - data_dir:/var/data
      - docker:/var/run/docker.sock
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    
volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
  docker_d:
  data_dir:
    driver: local
    driver_opts:
      type: bind
      device: ./data_dir
  docker:
    driver: local
    driver_opts:
      type: bind
      device: /var/run/docker.sock